name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  env:
    DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO